import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Details from '../Components/Details'
import Testimonial from '../Components/Testimonial'
import Introduction from '../Components/Introduction'
import Form from '../Components/Form'
import Contact from '../Components/Contact'
import Footer from '../Components/Footer'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >

        <Introduction />
        <Details />
        <Testimonial />
        <Form />
        <Contact />

      </main >


      <Footer />


    </div >
  )
}
